// Generated by gencpp from file beginner_tutorials/angles.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ANGLES_H
#define BEGINNER_TUTORIALS_MESSAGE_ANGLES_H

#include <ros/service_traits.h>


#include <beginner_tutorials/anglesRequest.h>
#include <beginner_tutorials/anglesResponse.h>


namespace beginner_tutorials
{

struct angles
{

typedef anglesRequest Request;
typedef anglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct angles
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::angles > {
  static const char* value()
  {
    return "d61f65b1d41fa5ce5b8822fbdbff89c7";
  }

  static const char* value(const ::beginner_tutorials::angles&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::angles > {
  static const char* value()
  {
    return "beginner_tutorials/angles";
  }

  static const char* value(const ::beginner_tutorials::angles&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::anglesRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::angles >
template<>
struct MD5Sum< ::beginner_tutorials::anglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::angles >::value();
  }
  static const char* value(const ::beginner_tutorials::anglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::anglesRequest> should match
// service_traits::DataType< ::beginner_tutorials::angles >
template<>
struct DataType< ::beginner_tutorials::anglesRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::angles >::value();
  }
  static const char* value(const ::beginner_tutorials::anglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::anglesResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::angles >
template<>
struct MD5Sum< ::beginner_tutorials::anglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::angles >::value();
  }
  static const char* value(const ::beginner_tutorials::anglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::anglesResponse> should match
// service_traits::DataType< ::beginner_tutorials::angles >
template<>
struct DataType< ::beginner_tutorials::anglesResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::angles >::value();
  }
  static const char* value(const ::beginner_tutorials::anglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ANGLES_H
