// Generated by gencpp from file beginner_tutorials/anglesMsg.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ANGLESMSG_H
#define BEGINNER_TUTORIALS_MESSAGE_ANGLESMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct anglesMsg_
{
  typedef anglesMsg_<ContainerAllocator> Type;

  anglesMsg_()
    : first(0)
    , second(0)
    , base(0)  {
    }
  anglesMsg_(const ContainerAllocator& _alloc)
    : first(0)
    , second(0)
    , base(0)  {
  (void)_alloc;
    }



   typedef int64_t _first_type;
  _first_type first;

   typedef int64_t _second_type;
  _second_type second;

   typedef int64_t _base_type;
  _base_type base;





  typedef boost::shared_ptr< ::beginner_tutorials::anglesMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::anglesMsg_<ContainerAllocator> const> ConstPtr;

}; // struct anglesMsg_

typedef ::beginner_tutorials::anglesMsg_<std::allocator<void> > anglesMsg;

typedef boost::shared_ptr< ::beginner_tutorials::anglesMsg > anglesMsgPtr;
typedef boost::shared_ptr< ::beginner_tutorials::anglesMsg const> anglesMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::anglesMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::anglesMsg_<ContainerAllocator1> & lhs, const ::beginner_tutorials::anglesMsg_<ContainerAllocator2> & rhs)
{
  return lhs.first == rhs.first &&
    lhs.second == rhs.second &&
    lhs.base == rhs.base;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::anglesMsg_<ContainerAllocator1> & lhs, const ::beginner_tutorials::anglesMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::anglesMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::anglesMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::anglesMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0496e8c0c35c632938a659f27c1ce0a3";
  }

  static const char* value(const ::beginner_tutorials::anglesMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0496e8c0c35c6329ULL;
  static const uint64_t static_value2 = 0x38a659f27c1ce0a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/anglesMsg";
  }

  static const char* value(const ::beginner_tutorials::anglesMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 first\n"
"int64 second\n"
"int64 base\n"
;
  }

  static const char* value(const ::beginner_tutorials::anglesMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
      stream.next(m.base);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct anglesMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::anglesMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::anglesMsg_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<int64_t>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<int64_t>::stream(s, indent + "  ", v.second);
    s << indent << "base: ";
    Printer<int64_t>::stream(s, indent + "  ", v.base);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ANGLESMSG_H
