// Generated by gencpp from file beginner_tutorials/encodersFeedback.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ENCODERSFEEDBACK_H
#define BEGINNER_TUTORIALS_MESSAGE_ENCODERSFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct encodersFeedback_
{
  typedef encodersFeedback_<ContainerAllocator> Type;

  encodersFeedback_()
    : first(0.0)
    , second(0.0)
    , base(0.0)  {
    }
  encodersFeedback_(const ContainerAllocator& _alloc)
    : first(0.0)
    , second(0.0)
    , base(0.0)  {
  (void)_alloc;
    }



   typedef double _first_type;
  _first_type first;

   typedef double _second_type;
  _second_type second;

   typedef double _base_type;
  _base_type base;





  typedef boost::shared_ptr< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct encodersFeedback_

typedef ::beginner_tutorials::encodersFeedback_<std::allocator<void> > encodersFeedback;

typedef boost::shared_ptr< ::beginner_tutorials::encodersFeedback > encodersFeedbackPtr;
typedef boost::shared_ptr< ::beginner_tutorials::encodersFeedback const> encodersFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::encodersFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::encodersFeedback_<ContainerAllocator1> & lhs, const ::beginner_tutorials::encodersFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.first == rhs.first &&
    lhs.second == rhs.second &&
    lhs.base == rhs.base;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::encodersFeedback_<ContainerAllocator1> & lhs, const ::beginner_tutorials::encodersFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0745d61b2a4b159f25fc57eee55861a2";
  }

  static const char* value(const ::beginner_tutorials::encodersFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0745d61b2a4b159fULL;
  static const uint64_t static_value2 = 0x25fc57eee55861a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/encodersFeedback";
  }

  static const char* value(const ::beginner_tutorials::encodersFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 first\n"
"float64 second\n"
"float64 base\n"
;
  }

  static const char* value(const ::beginner_tutorials::encodersFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
      stream.next(m.base);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encodersFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::encodersFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::encodersFeedback_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<double>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<double>::stream(s, indent + "  ", v.second);
    s << indent << "base: ";
    Printer<double>::stream(s, indent + "  ", v.base);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ENCODERSFEEDBACK_H
