// Generated by gencpp from file final_rover/armClient.msg
// DO NOT EDIT!


#ifndef FINAL_ROVER_MESSAGE_ARMCLIENT_H
#define FINAL_ROVER_MESSAGE_ARMCLIENT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace final_rover
{
template <class ContainerAllocator>
struct armClient_
{
  typedef armClient_<ContainerAllocator> Type;

  armClient_()
    : y(0.0)
    , command(0)
    , position(0)
    , pitch(0.0)
    , yaw(0.0)
    , gripper(0)  {
    }
  armClient_(const ContainerAllocator& _alloc)
    : y(0.0)
    , command(0)
    , position(0)
    , pitch(0.0)
    , yaw(0.0)
    , gripper(0)  {
  (void)_alloc;
    }



   typedef double _y_type;
  _y_type y;

   typedef uint8_t _command_type;
  _command_type command;

   typedef int16_t _position_type;
  _position_type position;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef int16_t _gripper_type;
  _gripper_type gripper;





  typedef boost::shared_ptr< ::final_rover::armClient_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::final_rover::armClient_<ContainerAllocator> const> ConstPtr;

}; // struct armClient_

typedef ::final_rover::armClient_<std::allocator<void> > armClient;

typedef boost::shared_ptr< ::final_rover::armClient > armClientPtr;
typedef boost::shared_ptr< ::final_rover::armClient const> armClientConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::final_rover::armClient_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::final_rover::armClient_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::final_rover::armClient_<ContainerAllocator1> & lhs, const ::final_rover::armClient_<ContainerAllocator2> & rhs)
{
  return lhs.y == rhs.y &&
    lhs.command == rhs.command &&
    lhs.position == rhs.position &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.gripper == rhs.gripper;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::final_rover::armClient_<ContainerAllocator1> & lhs, const ::final_rover::armClient_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace final_rover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::final_rover::armClient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::final_rover::armClient_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::armClient_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::armClient_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::armClient_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::armClient_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::final_rover::armClient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6475c3b95c87883ceb5174259fc15e38";
  }

  static const char* value(const ::final_rover::armClient_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6475c3b95c87883cULL;
  static const uint64_t static_value2 = 0xeb5174259fc15e38ULL;
};

template<class ContainerAllocator>
struct DataType< ::final_rover::armClient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "final_rover/armClient";
  }

  static const char* value(const ::final_rover::armClient_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::final_rover::armClient_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 y\n"
"char command\n"
"int16 position\n"
"float64 pitch\n"
"float64 yaw\n"
"int16 gripper\n"
;
  }

  static const char* value(const ::final_rover::armClient_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::final_rover::armClient_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.y);
      stream.next(m.command);
      stream.next(m.position);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.gripper);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct armClient_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::final_rover::armClient_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::final_rover::armClient_<ContainerAllocator>& v)
  {
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.position);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "gripper: ";
    Printer<int16_t>::stream(s, indent + "  ", v.gripper);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FINAL_ROVER_MESSAGE_ARMCLIENT_H
