// Generated by gencpp from file final_rover/encodersFeedback.msg
// DO NOT EDIT!


#ifndef FINAL_ROVER_MESSAGE_ENCODERSFEEDBACK_H
#define FINAL_ROVER_MESSAGE_ENCODERSFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace final_rover
{
template <class ContainerAllocator>
struct encodersFeedback_
{
  typedef encodersFeedback_<ContainerAllocator> Type;

  encodersFeedback_()
    : first(0.0)
    , second(0.0)  {
    }
  encodersFeedback_(const ContainerAllocator& _alloc)
    : first(0.0)
    , second(0.0)  {
  (void)_alloc;
    }



   typedef double _first_type;
  _first_type first;

   typedef double _second_type;
  _second_type second;





  typedef boost::shared_ptr< ::final_rover::encodersFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::final_rover::encodersFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct encodersFeedback_

typedef ::final_rover::encodersFeedback_<std::allocator<void> > encodersFeedback;

typedef boost::shared_ptr< ::final_rover::encodersFeedback > encodersFeedbackPtr;
typedef boost::shared_ptr< ::final_rover::encodersFeedback const> encodersFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::final_rover::encodersFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::final_rover::encodersFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::final_rover::encodersFeedback_<ContainerAllocator1> & lhs, const ::final_rover::encodersFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.first == rhs.first &&
    lhs.second == rhs.second;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::final_rover::encodersFeedback_<ContainerAllocator1> & lhs, const ::final_rover::encodersFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace final_rover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::final_rover::encodersFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::final_rover::encodersFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::encodersFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::encodersFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::encodersFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::encodersFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::final_rover::encodersFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8951f7da38088f2e93267537583f4e8";
  }

  static const char* value(const ::final_rover::encodersFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8951f7da38088f2ULL;
  static const uint64_t static_value2 = 0xe93267537583f4e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::final_rover::encodersFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "final_rover/encodersFeedback";
  }

  static const char* value(const ::final_rover::encodersFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::final_rover::encodersFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 first\n"
"float64 second\n"
;
  }

  static const char* value(const ::final_rover::encodersFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::final_rover::encodersFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first);
      stream.next(m.second);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct encodersFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::final_rover::encodersFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::final_rover::encodersFeedback_<ContainerAllocator>& v)
  {
    s << indent << "first: ";
    Printer<double>::stream(s, indent + "  ", v.first);
    s << indent << "second: ";
    Printer<double>::stream(s, indent + "  ", v.second);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FINAL_ROVER_MESSAGE_ENCODERSFEEDBACK_H
