// Generated by gencpp from file final_rover/roverServer.msg
// DO NOT EDIT!


#ifndef FINAL_ROVER_MESSAGE_ROVERSERVER_H
#define FINAL_ROVER_MESSAGE_ROVERSERVER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace final_rover
{
template <class ContainerAllocator>
struct roverServer_
{
  typedef roverServer_<ContainerAllocator> Type;

  roverServer_()
    : left(0)
    , right(0)  {
    }
  roverServer_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int64_t _left_type;
  _left_type left;

   typedef int64_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::final_rover::roverServer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::final_rover::roverServer_<ContainerAllocator> const> ConstPtr;

}; // struct roverServer_

typedef ::final_rover::roverServer_<std::allocator<void> > roverServer;

typedef boost::shared_ptr< ::final_rover::roverServer > roverServerPtr;
typedef boost::shared_ptr< ::final_rover::roverServer const> roverServerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::final_rover::roverServer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::final_rover::roverServer_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::final_rover::roverServer_<ContainerAllocator1> & lhs, const ::final_rover::roverServer_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::final_rover::roverServer_<ContainerAllocator1> & lhs, const ::final_rover::roverServer_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace final_rover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::final_rover::roverServer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::final_rover::roverServer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::roverServer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::roverServer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::roverServer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::roverServer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::final_rover::roverServer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10ec03ad83d596042691890fad8ead6e";
  }

  static const char* value(const ::final_rover::roverServer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10ec03ad83d59604ULL;
  static const uint64_t static_value2 = 0x2691890fad8ead6eULL;
};

template<class ContainerAllocator>
struct DataType< ::final_rover::roverServer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "final_rover/roverServer";
  }

  static const char* value(const ::final_rover::roverServer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::final_rover::roverServer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 left\n"
"int64 right\n"
;
  }

  static const char* value(const ::final_rover::roverServer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::final_rover::roverServer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct roverServer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::final_rover::roverServer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::final_rover::roverServer_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FINAL_ROVER_MESSAGE_ROVERSERVER_H
