// Generated by gencpp from file final_rover/RoverMsg.msg
// DO NOT EDIT!


#ifndef FINAL_ROVER_MESSAGE_ROVERMSG_H
#define FINAL_ROVER_MESSAGE_ROVERMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace final_rover
{
template <class ContainerAllocator>
struct RoverMsg_
{
  typedef RoverMsg_<ContainerAllocator> Type;

  RoverMsg_()
    : x(0.0)
    , y(0.0)
    , isPID(false)  {
    }
  RoverMsg_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , isPID(false)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef uint8_t _isPID_type;
  _isPID_type isPID;





  typedef boost::shared_ptr< ::final_rover::RoverMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::final_rover::RoverMsg_<ContainerAllocator> const> ConstPtr;

}; // struct RoverMsg_

typedef ::final_rover::RoverMsg_<std::allocator<void> > RoverMsg;

typedef boost::shared_ptr< ::final_rover::RoverMsg > RoverMsgPtr;
typedef boost::shared_ptr< ::final_rover::RoverMsg const> RoverMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::final_rover::RoverMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::final_rover::RoverMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::final_rover::RoverMsg_<ContainerAllocator1> & lhs, const ::final_rover::RoverMsg_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.isPID == rhs.isPID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::final_rover::RoverMsg_<ContainerAllocator1> & lhs, const ::final_rover::RoverMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace final_rover

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::final_rover::RoverMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::final_rover::RoverMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::RoverMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::final_rover::RoverMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::RoverMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::final_rover::RoverMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::final_rover::RoverMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dac2c668a77a0aca11621addd50fbbe9";
  }

  static const char* value(const ::final_rover::RoverMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdac2c668a77a0acaULL;
  static const uint64_t static_value2 = 0x11621addd50fbbe9ULL;
};

template<class ContainerAllocator>
struct DataType< ::final_rover::RoverMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "final_rover/RoverMsg";
  }

  static const char* value(const ::final_rover::RoverMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::final_rover::RoverMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"bool isPID\n"
;
  }

  static const char* value(const ::final_rover::RoverMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::final_rover::RoverMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.isPID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoverMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::final_rover::RoverMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::final_rover::RoverMsg_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "isPID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isPID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FINAL_ROVER_MESSAGE_ROVERMSG_H
