// Generated by gencpp from file beginner_tutorials/anglesResponse.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_ANGLESRESPONSE_H
#define BEGINNER_TUTORIALS_MESSAGE_ANGLESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct anglesResponse_
{
  typedef anglesResponse_<ContainerAllocator> Type;

  anglesResponse_()
    : check(false)  {
    }
  anglesResponse_(const ContainerAllocator& _alloc)
    : check(false)  {
  (void)_alloc;
    }



   typedef uint8_t _check_type;
  _check_type check;





  typedef boost::shared_ptr< ::beginner_tutorials::anglesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::anglesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct anglesResponse_

typedef ::beginner_tutorials::anglesResponse_<std::allocator<void> > anglesResponse;

typedef boost::shared_ptr< ::beginner_tutorials::anglesResponse > anglesResponsePtr;
typedef boost::shared_ptr< ::beginner_tutorials::anglesResponse const> anglesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::anglesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::anglesResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::anglesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.check == rhs.check;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::anglesResponse_<ContainerAllocator1> & lhs, const ::beginner_tutorials::anglesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::anglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::anglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::anglesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5df00fea9d1f39520fa0345cbde1b26";
  }

  static const char* value(const ::beginner_tutorials::anglesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5df00fea9d1f395ULL;
  static const uint64_t static_value2 = 0x20fa0345cbde1b26ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/anglesResponse";
  }

  static const char* value(const ::beginner_tutorials::anglesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool check\n"
"\n"
;
  }

  static const char* value(const ::beginner_tutorials::anglesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.check);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct anglesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::anglesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::anglesResponse_<ContainerAllocator>& v)
  {
    s << indent << "check: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.check);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_ANGLESRESPONSE_H
